services:
  - type: web
    name: superbull
    env: python
    plan: free
    buildCommand: pip install flask
    startCommand: python superbull_app.py
    envVars:
      - key: PORT
        value: 10000
